/* Generated by tools/genassets.py -- DO NOT EDIT BY HAND */
#ifndef ASSETS_H
#define ASSETS_H

#define CHR_SPRITES_LEN 1632
#define CHR_BG_LEN 1504
extern const unsigned char chr_sprites[CHR_SPRITES_LEN];
extern const unsigned char chr_bg[CHR_BG_LEN];
extern const unsigned char game_palette[32];

#define SPR_JIM_IDLE 1  /* 2x3 tiles */
#define SPR_JIM_WALK1 7  /* 2x3 tiles */
#define SPR_JIM_WALK2 13  /* 2x3 tiles */
#define SPR_JIM_JUMP 19  /* 2x3 tiles */
#define SPR_JIM_CROUCH 25  /* 2x2 tiles */
#define SPR_JIM_SWIPE 29  /* 2x3 tiles */
#define SPR_JIM_HURT 35  /* 2x3 tiles */
#define SPR_JIM_VICTORY 41  /* 2x3 tiles */
#define SPR_BAT1 47  /* 2x2 tiles */
#define SPR_BAT2 51  /* 2x2 tiles */
#define SPR_CAT1 55  /* 2x2 tiles */
#define SPR_CAT2 59  /* 2x2 tiles */
#define SPR_GNOME1 63  /* 2x2 tiles */
#define SPR_GNOME2 67  /* 2x2 tiles */
#define SPR_BAG 71  /* 2x2 tiles */
#define SPR_CANDLE 75  /* 1x2 tiles */
#define SPR_CAP 77  /* 1x1 tiles */
#define SPR_TOMATO 78  /* 1x1 tiles */
#define SPR_SPLAT 79  /* 2x1 tiles */
#define SPR_SHARD 81  /* 1x1 tiles */
#define SPR_SLASH 82  /* 1x1 tiles */
#define SPR_POOF1 83  /* 1x1 tiles */
#define SPR_POOF2 84  /* 1x1 tiles */
#define SPR_SNACK 85  /* 1x1 tiles */
#define SPR_BIGSNACK 86  /* 2x2 tiles */
#define SPR_BURRITO 90  /* 1x1 tiles */
#define SPR_GOLD 91  /* 2x2 tiles */
#define SPR_MYSTERY 95  /* 1x1 tiles */
#define SPR_LID 96  /* 4x1 tiles */
#define SPR_EYE 100  /* 1x1 tiles */
#define SPR_GARB 101  /* 1x1 tiles */

#define FONT_A 1
#define FONT_0 27
#define FONT_PERIOD 37
#define FONT_BANG 38
#define FONT_DASH 39
#define FONT_APOS 40
#define FONT_COMMA 41
#define FONT_COLON 42

#define TILE_PIP_FULL 43
#define TILE_PIP_EMPTY 44
#define TILE_SNACK_ICON 45
#define TILE_ICON_CAP 46
#define TILE_ICON_TOMATO 47

#define MT_COUNT 16
#define MT_SKY 0
#define MT_BRICK 1
#define MT_DIRT 2
#define MT_PLATFORM 3
#define MT_MOON 4
#define MT_FENCE 5
#define MT_TRASHPILE 6
#define MT_DOORTOP 7
#define MT_DOORBOTTOM 8
#define MT_CANS 9
#define MT_BENCH 10
#define MT_GLASS 11
#define MT_DUMPRIM 12
#define MT_DUMPBODY 13
#define MT_DUMPGLOW 14
#define MT_WINDOW 15
extern const unsigned char mt_tl[MT_COUNT];
extern const unsigned char mt_tr[MT_COUNT];
extern const unsigned char mt_bl[MT_COUNT];
extern const unsigned char mt_br[MT_COUNT];
extern const unsigned char mt_coll[MT_COUNT];

#define COLL_NONE 0
#define COLL_SOLID 1
#define COLL_PLATFORM 2
#define COLL_HAZARD 3
#define COLL_DOOR 4

#define SP_BAT 1
#define SP_CAT 2
#define SP_GNOME 3
#define SP_BAG 4
#define SP_CANDLE 5
#define SP_SNACK 6
#define SP_BIGSNACK 7
#define SP_BURRITO 8
#define SP_GOLD 9
#define SP_WEAPON_CAP 10
#define SP_WEAPON_TOMATO 11

#define ROOM_COUNT 5
typedef struct {
    const unsigned char *map;    /* 240 metatile ids */
    const unsigned char *attr;   /* 64 attribute bytes */
    const unsigned char *spawns; /* type,x,y triples, 0xFF end */
    unsigned char start_x, start_y; /* player start, metatile coords */
    unsigned char door_dest;     /* room index, 0xFF = victory */
} RoomDef;
extern const RoomDef rooms[ROOM_COUNT];

#define NUM_NOTES 60
extern const unsigned char period_lo[NUM_NOTES + 1];
extern const unsigned char period_hi[NUM_NOTES + 1];
#define SONG_COUNT 5
extern const unsigned char * const song_streams[SONG_COUNT][4];

#endif /* ASSETS_H */
