/* audio.c -- tiny APU driver: three music channels (pulse1 melody,
   pulse2 harmony, triangle bass) + noise drums, with SFX that borrow
   pulse2 or noise and give them back when done.

   Song data (generated by tools/genassets.py, in PRG bank 0) is a byte
   stream per channel: [note, dur]* then 0xFF = loop or 0xFE = end.
   Note 0 = rest; noise notes 1/2/3 = kick/snare/hat. */
#include "nes.h"
#include "audio.h"
#include "assets.h"

/* channel indices */
#define CH_P1 0
#define CH_P2 1
#define CH_TRI 2
#define CH_NOI 3

static const unsigned char *ch_base[4];
static unsigned int ch_pos[4];
static unsigned char ch_dur[4];
static unsigned char ch_note[4];
static unsigned char ch_done[4];
static unsigned char cur_song;

/* --- SFX ---------------------------------------------------------- */
/* Pulse SFX: arrays of note indices played one per frame (0 = rest,
   0xFF = end). Noise SFX: (period << 4) | volume per frame, 0xFF = end. */

static const unsigned char sfx_jump_d[]   = { 20, 25, 29, 32, 34, 36, 0xFF };
static const unsigned char sfx_pickup_d[] = { 41, 41, 46, 46, 48, 0xFF };
static const unsigned char sfx_door_d[]   = { 13, 13, 8, 8, 6, 6, 0xFF };
static const unsigned char sfx_bosshurt_d[] = { 10, 8, 10, 8, 6, 6, 5, 5, 0xFF };

static const unsigned char sfx_swipe_d[]  = { 0x2A, 0x37, 0x44, 0x22, 0xFF };
static const unsigned char sfx_hurt_d[]   = { 0xC9, 0xC8, 0xD7, 0xD6, 0xE5, 0xE4, 0xE2, 0xFF };
static const unsigned char sfx_hit_d[]    = { 0x66, 0x54, 0x32, 0xFF };
static const unsigned char sfx_die_d[]    = { 0x88, 0x97, 0xA6, 0xB5, 0xC4, 0xD3, 0xE2, 0xE1, 0xFF };
static const unsigned char sfx_throw_d[]  = { 0x43, 0x33, 0x22, 0xFF };
static const unsigned char sfx_splat_d[]  = { 0xD8, 0xD7, 0xE6, 0xE5, 0xE3, 0xE2, 0xFF };
static const unsigned char sfx_slam_d[]   = { 0xE9, 0xE9, 0xF8, 0xF8, 0xF7, 0xF6, 0xF5, 0xF4, 0xF3, 0xF2, 0xF1, 0xFF };

/* id -> data, channel (0 = pulse2, 1 = noise), priority */
static const unsigned char *const sfx_data[] = {
    0, sfx_swipe_d, sfx_jump_d, sfx_pickup_d, sfx_hurt_d, sfx_hit_d,
    sfx_die_d, sfx_throw_d, sfx_splat_d, sfx_door_d, sfx_slam_d,
    sfx_bosshurt_d
};
static const unsigned char sfx_chan[] = { 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0 };
static const unsigned char sfx_prio[] = { 0, 2, 2, 3, 6, 1, 4, 2, 3, 5, 7, 6 };

static unsigned char sfx_id, sfx_pos;

/* ------------------------------------------------------------------ */

static void ch_silence(unsigned char ch) {
    switch (ch) {
    case CH_P1: SQ1_VOL = 0x30; break;
    case CH_P2: SQ2_VOL = 0x30; break;
    case CH_TRI: TRI_LINEAR = 0x80; break;
    case CH_NOI: NOISE_VOL = 0x30; break;
    }
}

static void ch_play(unsigned char ch, unsigned char note) {
    if (!note) {
        ch_silence(ch);
        return;
    }
    switch (ch) {
    case CH_P1:
        SQ1_VOL = 0xB6;                 /* duty 50%, const vol 6 */
        SQ1_LO = period_lo[note];
        SQ1_HI = period_hi[note];
        break;
    case CH_P2:
        SQ2_VOL = 0x74;                 /* duty 25%, const vol 4 */
        SQ2_LO = period_lo[note];
        SQ2_HI = period_hi[note];
        break;
    case CH_TRI:
        TRI_LINEAR = 0xFF;
        TRI_LO = period_lo[note];
        TRI_HI = period_hi[note];
        break;
    case CH_NOI:
        /* drums: hardware envelope decays on its own */
        if (note == 1) {                /* kick */
            NOISE_VOL = 0x04;
            NOISE_LO = 0x0C;
        } else if (note == 2) {         /* snare */
            NOISE_VOL = 0x03;
            NOISE_LO = 0x07;
        } else {                        /* hat */
            NOISE_VOL = 0x01;
            NOISE_LO = 0x02;
        }
        NOISE_HI = 0x08;
        break;
    }
}

void audio_init(void) {
    SND_CHN = 0x0F;
    SQ1_SWEEP = 0x08;   /* sweep off (negate mode: no low-period muting) */
    SQ2_SWEEP = 0x08;
    ch_silence(0);
    ch_silence(1);
    ch_silence(2);
    ch_silence(3);
    cur_song = SONG_NONE;
    sfx_id = SFX_NONE;
}

void audio_song(unsigned char id) {
    unsigned char ch;
    /* looping songs keep playing across room loads; stings always restart */
    if (id == cur_song && id >= SONG_TITLE && id <= SONG_BOSS) return;
    cur_song = id;
    for (ch = 0; ch < 4; ++ch) {
        ch_pos[ch] = 0;
        ch_dur[ch] = 1;
        ch_note[ch] = 0;
        ch_done[ch] = 0;
        ch_base[ch] = (id == SONG_NONE) ? 0 : song_streams[id - 1][ch];
        if (!ch_base[ch]) {
            ch_done[ch] = 1;
            ch_silence(ch);
        }
    }
}

void audio_sfx(unsigned char id) {
    if (sfx_id != SFX_NONE && sfx_prio[id] < sfx_prio[sfx_id]) return;
    sfx_id = id;
    sfx_pos = 0;
}

static void music_tick(void) {
    unsigned char ch, note;
    const unsigned char *p;
    for (ch = 0; ch < 4; ++ch) {
        if (ch_done[ch]) continue;
        if (--ch_dur[ch]) continue;
        p = ch_base[ch];
    fetch:
        note = p[ch_pos[ch]];
        if (note == 0xFF) {
            ch_pos[ch] = 0;
            goto fetch;
        }
        if (note == 0xFE) {
            ch_done[ch] = 1;
            ch_silence(ch);
            continue;
        }
        ch_note[ch] = note;
        ch_dur[ch] = p[ch_pos[ch] + 1];
        ch_pos[ch] += 2;
        /* while an SFX owns a channel, track the stream but stay quiet */
        if (sfx_id != SFX_NONE) {
            if (ch == CH_P2 && sfx_chan[sfx_id] == 0) continue;
            if (ch == CH_NOI && sfx_chan[sfx_id] == 1) continue;
        }
        ch_play(ch, note);
    }
}

static void sfx_tick(void) {
    unsigned char v;
    const unsigned char *d;
    if (sfx_id == SFX_NONE) return;
    d = sfx_data[sfx_id];
    v = d[sfx_pos++];
    if (v == 0xFF) {
        /* hand the channel back to the music */
        if (sfx_chan[sfx_id] == 0) {
            ch_silence(CH_P2);
            if (!ch_done[CH_P2]) ch_play(CH_P2, ch_note[CH_P2]);
        } else {
            ch_silence(CH_NOI);
        }
        sfx_id = SFX_NONE;
        return;
    }
    if (sfx_chan[sfx_id] == 0) {
        if (!v) {
            SQ2_VOL = 0x30;
        } else {
            SQ2_VOL = 0x78;             /* duty 25%, vol 8 */
            SQ2_LO = period_lo[v];
            SQ2_HI = period_hi[v];
        }
    } else {
        NOISE_VOL = 0x30 | (v & 0x0F);
        NOISE_LO = v >> 4;
        NOISE_HI = 0x08;
    }
}

void audio_frame(void) {
    music_tick();
    sfx_tick();
}
